First version of new york times clone
TommyM0ntana/newyorktimes pull request #2
Opened 2019-09-23 22:46 UTC by TommyM0ntana

2019-09-24 15:53 UTC, tomzacchia commented
- W3 HTML validation (Note, we did not add any empty elements to get  rid of warnings since they would be redundant) 
![Screen Shot 2019-09-24 at 11 50 57 AM](https://user-images.githubusercontent.com/26035225/65528151-dd0a3980-dec1-11e9-86da-cd092b34b0c4.png)

- The theory of inflation infographic. We designed this part for 1440x604 resolution
![Screen Shot 2019-09-24 at 11 52 25 AM](https://user-images.githubusercontent.com/26035225/65528203-f01d0980-dec1-11e9-905a-1100c7815020.png)

2019-09-24 18:01 UTC, Forison reviewed
# pull request under review by Addo

2019-09-24 19:11 UTC, Forison requested changes
Hi Team, 👋👋
Your project looks nice, am impress, but there are a few additions to make.
- #### **[REQUIRED]** README 🙂 
Your readme file is supposed to be descriptive enough(readme has to describe the project you have worked on in detail. It can include information on collaborators, the technology used, why the project was designed, how to access, etc... ).[readme](https://github.com/Forison/Using-Bootstrap)

- #### **[REQUIRED]** PROJECT IMPLEMENTATION 🙂
your project does not display all the contents found on the original. Your project ends with the theory of inflation.
* There is no footer
>note here the footer is the fixed bottom navbar like element at the bottom of your screen with inscription "access more of the times by creating account
* I also noticed that you used inline styling in a couple of places in your code. Inline styling is a bad practice you should shy away from using them. all styling must be done in your ```main.css```  per this project.
###  VALIDATOR WARNING ISSUES
There are two ways to avoid this warning:
 * Either you do what you suggested by adding  ```<h2> -<h6>```, which would be of course obsolete😔 or
* Replace those ```section```  tags with ```div``` (I  recommend this approach)🙂 

> please don't forget to comment your pull request don't leave it empty
# Kindly make those changes and submit for review again
Happy coding

2019-09-24 19:15 UTC, Forison requested changes

2019-09-24 19:15 UTC, Forison commented on index.html
> +        <p style="font-size: 12px">
> inline styling, not good practice

2019-09-24 19:15 UTC, Forison commented on index.html
> +    <div class="theories" style="background-image: url('./images/inflation.png')">
> inline styling, not good practice

2019-09-24 19:15 UTC, Forison commented on index.html
> +          <span style="font-weight: bold"> THE UNIVERSE </span>
> inline styling, not good practice

2019-09-24 19:15 UTC, Forison commented on index.html
> +          <span style="font-weight: bold"> THE UNIVERSE </span>
> rectify all other inline stylings as mentioned in the main review

2019-09-25 22:23 UTC, tomzacchia commented
- updated readme
- added footer and floating sign in navbar thingy
- removed inline styling
- for the w3 warnings, we left the sections as they were since it is a requirement to use semantic HTML

2019-09-26 04:47 UTC, uche-inyama requested changes
#### Hi Tommy, :wave: 

I can see you have implemented some of the changes suggested by my colleague. However, you missed some. 

- [ ] Your html document is not valid, there still errors showing up, when passed through  [html validator](https://validator.w3.org).

- [ ] There are inline styling in your html document, all css implementation should be done in your main.css.

#### Implement these changes, then submit another form for code review.

2019-09-26 15:34 UTC, tomzacchia commented
![Screen Shot 2019-09-26 at 11 31 30 AM](https://user-images.githubusercontent.com/26035225/65702825-aa8f4680-e051-11e9-991c-4bd5f36b1b70.png)

2019-09-26 17:40 UTC, uche-inyama approved these changes
Hi Tommy, we are good now :slightly_smiling_face: 

#### This is project is approved
**```Go ahead and merge to master branch```** :clap: :clap:

2019-09-26 17:45 UTC, merged